// <auto-generated />
using MVC_EduScanner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_EduScanner.Migrations
{
    [DbContext(typeof(App_DbContext))]
    [Migration("20250316212838_EduScanner_migration")]
    partial class EduScanner_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_EduScanner.Models.Prowadzacy", b =>
                {
                    b.Property<int>("ProwadzacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProwadzacyID"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProwadzacyID");

                    b.ToTable("Prowadzacy");
                });

            modelBuilder.Entity("MVC_EduScanner.Models.Przedmiot", b =>
                {
                    b.Property<int>("PrzedmiotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrzedmiotID"));

                    b.Property<string>("NazwaPrzedmiotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrzedmiotID");

                    b.ToTable("Przedmioty");
                });

            modelBuilder.Entity("MVC_EduScanner.Models.PrzedmiotProwadzacy", b =>
                {
                    b.Property<int>("PrzedmiotID")
                        .HasColumnType("int");

                    b.Property<int>("ProwadzacyID")
                        .HasColumnType("int");

                    b.HasKey("PrzedmiotID", "ProwadzacyID");

                    b.HasIndex("ProwadzacyID");

                    b.ToTable("PrzedmiotProwadzacy");
                });

            modelBuilder.Entity("MVC_EduScanner.Models.PrzedmiotProwadzacy", b =>
                {
                    b.HasOne("MVC_EduScanner.Models.Prowadzacy", "Prowadzacy")
                        .WithMany("PrzedmiotProwadzacy")
                        .HasForeignKey("ProwadzacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_EduScanner.Models.Przedmiot", "Przedmiot")
                        .WithMany("PrzedmiotProwadzacy")
                        .HasForeignKey("PrzedmiotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prowadzacy");

                    b.Navigation("Przedmiot");
                });

            modelBuilder.Entity("MVC_EduScanner.Models.Prowadzacy", b =>
                {
                    b.Navigation("PrzedmiotProwadzacy");
                });

            modelBuilder.Entity("MVC_EduScanner.Models.Przedmiot", b =>
                {
                    b.Navigation("PrzedmiotProwadzacy");
                });
#pragma warning restore 612, 618
        }
    }
}
